/**
 * Signal performance — honest accounting of past signals.
 *
 * The product question this page answers: "If I had executed every
 * AUTO/REVIEW signal Helix ever fired, what would have happened?"
 *
 * What we measure
 *   - Volume: how many signals at each tier
 *   - Resolution: target_hit / stop_hit / flat / dismissed / blocked
 *   - Realized P&L: average pct move from entry to outcome
 *   - Win rate among resolved (excludes flat / blocked / dismissed)
 *
 * Design language matches /briefing — Fraunces hero, hairlines, mono
 * kickers, generous spacing.
 */
import { Shell } from "@/components/layout/Shell";
import { all, get } from "@/lib/db/client";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

interface TierRow {
  tier: string;
  total: number;
  target_hit: number;
  stop_hit: number;
  flat: number;
  blocked: number;
  dismissed: number;
  pending: number;
  avg_realized_pct: number | null;
}

interface SubtypeRow {
  catalyst_subtype: string;
  n: number;
  wins: number;
  losses: number;
  flat: number;
  avg_realized_pct: number | null;
}

interface RecentRow {
  signal_id: string;
  asset: string;
  direction: string;
  tier: string;
  catalyst_subtype: string;
  outcome: string | null;
  realized_pct: number | null;
  generated_at: number;
  outcome_at: number | null;
  /** news_events.title — what the agent was reasoning about when the
   *  signal fired. Trimmed to a single line on the table; the audit
   *  page has the full version. */
  title: string | null;
  /** When NULL the realized_pct is meaningless (no kline data for the
   *  asset, e.g. tok-hype / idx-ssidefi). The UI renders "—" instead
   *  of a misleading 0.00%. */
  price_at_outcome: number | null;
}

/**
 * Defensive filter applied to every rollup on this page:
 *
 *   - Only count signals fired since `JUNE_2026_EPOCH_MS` — earlier
 *     rows were generated by pre-prod calibration runs with stale
 *     klines, missing fields, and a different signal-gen path; they
 *     drag the headline numbers around in misleading ways. Buildathon
 *     window starts here.
 *   - Drop shadow-v2 backtest rows (framework_version='v2' or signal_id
 *     ending '-shadow-v2'). Internal A/B-compare data, not user-facing.
 *   - Drop `regulatory_statement` + `earnings_reaction` — both produce
 *     mostly-noise signals.
 *   - Dedupe to one row per (asset, day, subtype, direction) bucket
 *     so the signal-gen "fires 74× on one catalyst" bug doesn't
 *     pollute averages.
 *
 * Companion one-off purges: scripts/dedupe-signal-outcomes.mjs and
 * scripts/backfill-june-outcomes.mjs.
 */
// 2026-06-01 00:00 UTC = Date.UTC(2026, 5, 1). The earlier literal
// here was 1780056000000 which is actually 2026-05-29 12:00 UTC and
// was leaking late-May signals into the June window. Hard-set to
// the correct value so a future fingers-on-the-keyboard miscalc
// can't reintroduce the slip.
const JUNE_2026_EPOCH_MS = 1780272000000;

const CANONICAL = `signal_outcomes_canonical AS (
  SELECT o.*
  FROM signal_outcomes o
  WHERE COALESCE(o.framework_version, 'v1') = 'v1'
    AND o.signal_id NOT LIKE '%-shadow-v2'
    AND o.generated_at >= ${JUNE_2026_EPOCH_MS}
    AND (o.catalyst_subtype IS NULL
         OR o.catalyst_subtype NOT IN ('regulatory_statement', 'earnings_reaction'))
    AND o.signal_id = (
      SELECT MIN(o2.signal_id) FROM signal_outcomes o2
      WHERE o2.asset_id = o.asset_id
        AND COALESCE(o2.catalyst_subtype, '') = COALESCE(o.catalyst_subtype, '')
        AND o2.direction = o.direction
        AND substr(datetime(o2.generated_at/1000,'unixepoch'),1,10)
            = substr(datetime(o.generated_at/1000,'unixepoch'),1,10)
        AND COALESCE(o2.framework_version, 'v1') = 'v1'
        AND o2.signal_id NOT LIKE '%-shadow-v2'
        AND o2.generated_at >= ${JUNE_2026_EPOCH_MS}
        AND (o2.catalyst_subtype IS NULL
             OR o2.catalyst_subtype NOT IN ('regulatory_statement', 'earnings_reaction'))
    )
)`;

async function loadTierStats(): Promise<TierRow[]> {
  return await all<TierRow>(`
    WITH ${CANONICAL}
    SELECT tier,
           COUNT(*) AS total,
           SUM(CASE WHEN outcome = 'target_hit' THEN 1 ELSE 0 END) AS target_hit,
           SUM(CASE WHEN outcome = 'stop_hit'   THEN 1 ELSE 0 END) AS stop_hit,
           SUM(CASE WHEN outcome = 'flat'       THEN 1 ELSE 0 END) AS flat,
           SUM(CASE WHEN outcome = 'blocked'    THEN 1 ELSE 0 END) AS blocked,
           SUM(CASE WHEN outcome = 'dismissed'  THEN 1 ELSE 0 END) AS dismissed,
           SUM(CASE WHEN outcome IS NULL        THEN 1 ELSE 0 END) AS pending,
           AVG(CASE WHEN outcome IN ('target_hit','stop_hit')
                  OR (outcome = 'flat' AND price_at_outcome IS NOT NULL)
                  THEN realized_pct END) AS avg_realized_pct
    FROM signal_outcomes_canonical
    GROUP BY tier
    ORDER BY
      CASE tier WHEN 'auto' THEN 1 WHEN 'review' THEN 2 WHEN 'info' THEN 3 ELSE 4 END
  `);
}

async function loadSubtypeStats(): Promise<SubtypeRow[]> {
  return await all<SubtypeRow>(`
    WITH ${CANONICAL}
    SELECT catalyst_subtype,
           COUNT(*) AS n,
           SUM(CASE WHEN outcome = 'target_hit' THEN 1 ELSE 0 END) AS wins,
           SUM(CASE WHEN outcome = 'stop_hit'   THEN 1 ELSE 0 END) AS losses,
           SUM(CASE WHEN outcome = 'flat'       THEN 1 ELSE 0 END) AS flat,
           AVG(CASE WHEN outcome IN ('target_hit','stop_hit')
                  OR (outcome = 'flat' AND price_at_outcome IS NOT NULL)
                  THEN realized_pct END) AS avg_realized_pct
    FROM signal_outcomes_canonical
    WHERE catalyst_subtype IS NOT NULL AND catalyst_subtype != ''
      AND outcome IS NOT NULL
    GROUP BY catalyst_subtype
    HAVING n >= 2
    ORDER BY n DESC
  `);
}

async function loadRecent(): Promise<RecentRow[]> {
  return await all<RecentRow>(`
    WITH ${CANONICAL}
    SELECT o.signal_id, o.asset_id AS asset, o.direction, o.tier,
           o.catalyst_subtype, o.outcome, o.realized_pct,
           o.generated_at, o.outcome_at, o.price_at_outcome,
           n.title AS title
    FROM signal_outcomes_canonical o
    LEFT JOIN signals s ON s.id = o.signal_id
    LEFT JOIN news_events n ON n.id = s.triggered_by_event_id
    WHERE o.outcome IN ('target_hit','stop_hit','flat')
    ORDER BY o.generated_at DESC
    LIMIT 25
  `);
}

async function loadTotals() {
  const r = await get<{
    total: number;
    resolved: number;
    pending: number;
    avg_pct: number | null;
    target_hits: number;
    stop_hits: number;
    flats: number;
    // Realized-ROI-based win accounting. A "win" is a signal that
    // actually closed positive at expiry (realized_pct > 0), NOT one
    // that merely touched its target level intraday. `priced_resolved`
    // excludes rows we couldn't price (no kline at expiry).
    realized_wins: number;
    priced_resolved: number;
  }>(`
    WITH ${CANONICAL}
    SELECT COUNT(*) AS total,
           SUM(CASE WHEN outcome IS NOT NULL THEN 1 ELSE 0 END) AS resolved,
           SUM(CASE WHEN outcome IS NULL THEN 1 ELSE 0 END) AS pending,
           AVG(CASE WHEN outcome IN ('target_hit','stop_hit')
                  OR (outcome = 'flat' AND price_at_outcome IS NOT NULL)
                  THEN realized_pct END) AS avg_pct,
           SUM(CASE WHEN outcome = 'target_hit' THEN 1 ELSE 0 END) AS target_hits,
           SUM(CASE WHEN outcome = 'stop_hit' THEN 1 ELSE 0 END) AS stop_hits,
           SUM(CASE WHEN outcome = 'flat' THEN 1 ELSE 0 END) AS flats,
           SUM(CASE WHEN (outcome IN ('target_hit','stop_hit')
                          OR (outcome = 'flat' AND price_at_outcome IS NOT NULL))
                         AND realized_pct > 0
                    THEN 1 ELSE 0 END) AS realized_wins,
           SUM(CASE WHEN outcome IN ('target_hit','stop_hit')
                  OR (outcome = 'flat' AND price_at_outcome IS NOT NULL)
                  THEN 1 ELSE 0 END) AS priced_resolved
    FROM signal_outcomes_canonical
  `);
  return r;
}

function fmtPct(x: number | null | undefined, withSign = false): string {
  if (x == null) return "—";
  const sign = withSign && x > 0 ? "+" : "";
  return `${sign}${x.toFixed(2)}%`;
}

// Human labels for the internal catalyst-subtype slugs.
const CATALYST_LABELS: Record<string, string> = {
  macro_print: "Macro print",
  treasury_action: "Treasury buy",
  etf_flow_reaction: "ETF flow",
  partnership_announcement: "Partnership",
  tech_update: "Tech / product",
  whale_flow: "Whale flow",
  regulatory_statement: "Regulatory",
  earnings_reaction: "Earnings",
  listing_event: "Listing",
  security_incident: "Security",
};
function humanCatalyst(s: string | null | undefined): string {
  if (!s) return "—";
  return (
    CATALYST_LABELS[s] ??
    s.charAt(0).toUpperCase() + s.slice(1).replace(/_/g, " ")
  );
}

// ─── Design tokens ──
const COLORS = {
  pos: "#34c39a",
  neg: "#e25b66",
  text: "#e7e5e0",
  muted: "#8a857d",
  dim: "#5c5852",
  line: "rgba(255,255,255,0.07)",
};

const KICKER = {
  fontFamily: "var(--font-jetbrains-mono)",
  fontSize: 10,
  letterSpacing: "0.22em",
  textTransform: "uppercase" as const,
  color: COLORS.muted,
};

const HEADLINE = {
  fontFamily: "var(--font-fraunces)",
  fontSize: 32,
  lineHeight: 1.15,
  color: COLORS.text,
  letterSpacing: "-0.01em",
};

function HairlineHeader({ kicker, headline, note }: { kicker: string; headline: string; note?: string }) {
  return (
    <div style={{ paddingBottom: 28, marginBottom: 28, borderBottom: `1px solid ${COLORS.line}` }}>
      <div style={KICKER}>{kicker}</div>
      <h1 style={{ ...HEADLINE, marginTop: 10 }}>{headline}</h1>
      {note && (
        <p style={{ marginTop: 12, color: COLORS.muted, fontSize: 14, lineHeight: 1.6, maxWidth: 720 }}>{note}</p>
      )}
    </div>
  );
}

export default async function PerformancePage() {
  const [totals, tiers, subtypes, recent] = await Promise.all([
    loadTotals(),
    loadTierStats(),
    loadSubtypeStats(),
    loadRecent(),
  ]);

  // Win rate keys off the ACTUAL realized ROI at expiry (close-to-close),
  // not whether a target/stop level was touched intraday. A signal that
  // dipped to its stop but recovered to close green counts as a win.
  const winRate =
    totals && totals.priced_resolved > 0
      ? totals.realized_wins / totals.priced_resolved
      : null;

  // Column maxes for the "Avg realized" magnitude bars — so the strongest
  // and weakest tiers / catalysts read as length, not just a signed number.
  const tierRealizedMax = Math.max(
    0,
    ...tiers.map((t) => Math.abs(t.avg_realized_pct ?? 0)),
  );
  const subtypeRealizedMax = Math.max(
    0,
    ...subtypes.map((s) => Math.abs(s.avg_realized_pct ?? 0)),
  );
  const recentRealizedMax = Math.max(
    0,
    ...recent
      .filter((r) => !(r.outcome === "flat" && r.price_at_outcome == null))
      .map((r) => Math.abs(r.realized_pct ?? 0)),
  );

  return (
    <Shell>
      <HairlineHeader
        kicker="Signal Performance"
        headline="What happened to the signals we fired"
        note="Honest accounting. Includes everything Helix ever proposed — AUTO, REVIEW, INFO. Realized return is the actual close-to-close ROI at the signal's expiry — not the target/stop we set up front. The Target / Stop / Flat label only marks which level (if any) price touched intraday; a signal can touch its stop and still close green. Win rate = share of priced signals that closed positive at expiry. Blocked = the pre-save invariant gate refused the signal at fire time. Dismissed = the lifecycle sweeper closed it."
      />

      {/* Top-line totals — auto-fit so it drops to 2×2 / 1-col on narrow screens */}
      <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(150px, 1fr))", gap: 24, marginBottom: 36 }}>
        <Stat
          kicker="Total signals"
          value={String(totals?.total ?? 0)}
          note={`${totals?.resolved ?? 0} resolved · ${totals?.pending ?? 0} pending`}
        />
        <Stat
          kicker="Win rate"
          value={winRate == null ? "—" : `${Math.round(winRate * 100)}%`}
          note={`${totals?.realized_wins ?? 0} closed up / ${totals?.priced_resolved ?? 0} priced at expiry`}
          color={winRate == null ? COLORS.text : winRate > 0.5 ? COLORS.pos : COLORS.neg}
        />
        <Stat
          kicker="Avg realized"
          value={fmtPct(totals?.avg_pct ?? null, true)}
          note="across resolved outcomes"
          color={
            totals?.avg_pct == null
              ? COLORS.text
              : totals.avg_pct > 0
                ? COLORS.pos
                : COLORS.neg
          }
        />
        <Stat
          kicker="Flat rate"
          value={
            totals && totals.resolved > 0
              ? `${Math.round((totals.flats / totals.resolved) * 100)}%`
              : "—"
          }
          note="expired without hitting target or stop"
        />
      </div>

      {/* By tier */}
      <Section title="By tier" kicker="Breakdown">
        <SimpleTable
          head={["Tier", "Total", "Target hit", "Stop hit", "Flat", "Avg realized"]}
          rows={tiers.map((t) => [
            <span key="t" style={{ textTransform: "uppercase", letterSpacing: "0.1em", fontSize: 11 }}>
              {t.tier}
            </span>,
            String(t.total),
            <Cell key="w" v={t.target_hit} color={COLORS.pos} />,
            <Cell key="l" v={t.stop_hit} color={COLORS.neg} />,
            String(t.flat),
            <MagBar key="r" value={t.avg_realized_pct} max={tierRealizedMax} />,
          ])}
        />
      </Section>

      {/* By subtype */}
      {subtypes.length > 0 && (
        <Section title="By catalyst subtype" kicker="What works">
          <SimpleTable
            head={["Catalyst", "n", "Wins", "Losses", "Flat", "Avg realized"]}
            rows={subtypes.map((s) => [
              humanCatalyst(s.catalyst_subtype),
              String(s.n),
              <Cell key="w" v={s.wins} color={COLORS.pos} />,
              <Cell key="l" v={s.losses} color={COLORS.neg} />,
              String(s.flat),
              <MagBar key="r" value={s.avg_realized_pct} max={subtypeRealizedMax} />,
            ])}
          />
        </Section>
      )}

      {/* Recent resolved */}
      <Section title="Recent resolved signals" kicker="Receipts">
        {recent.length === 0 ? (
          <p style={{ color: COLORS.muted, fontSize: 14 }}>No resolved signals yet.</p>
        ) : (
          <SimpleTable
            head={["Date", "Asset", "Dir", "Headline", "Outcome", "Realized"]}
            rows={recent.map((r) => [
              new Date(r.generated_at).toISOString().slice(0, 10),
              <a
                key="a"
                href={`/signal/${r.signal_id}`}
                style={{
                  color: COLORS.text,
                  textDecoration: "none",
                  borderBottom: `1px dotted ${COLORS.muted}`,
                }}
              >
                {r.asset}
              </a>,
              <span
                key="d"
                style={{ color: r.direction === "long" ? COLORS.pos : COLORS.neg, fontSize: 11 }}
              >
                {r.direction.toUpperCase()}
              </span>,
              <HeadlineCell
                key="h"
                title={r.title}
                fallback={humanCatalyst(r.catalyst_subtype)}
                href={`/signal/${r.signal_id}`}
              />,
              <OutcomeBadge key="o" outcome={r.outcome ?? ""} />,
              (() => {
                // Without a price_at_outcome the realized_pct=0 is a
                // placeholder, not a real flat. Show "—" to be honest.
                const unpriceable =
                  r.outcome === "flat" && r.price_at_outcome == null;
                if (unpriceable) {
                  return (
                    <span
                      key="r"
                      title="no kline data for this asset"
                      style={{ color: COLORS.muted }}
                    >
                      —
                    </span>
                  );
                }
                return (
                  <MagBar key="r" value={r.realized_pct} max={recentRealizedMax} />
                );
              })(),
            ])}
          />
        )}
      </Section>
    </Shell>
  );
}

function Stat({ kicker, value, note, color }: { kicker: string; value: string; note?: string; color?: string }) {
  return (
    <div>
      <div style={KICKER}>{kicker}</div>
      <div
        style={{
          fontFamily: "var(--font-fraunces)",
          fontSize: 36,
          lineHeight: 1.1,
          color: color ?? COLORS.text,
          marginTop: 8,
          letterSpacing: "-0.01em",
        }}
      >
        {value}
      </div>
      {note && (
        <div style={{ marginTop: 6, color: COLORS.muted, fontSize: 12 }}>{note}</div>
      )}
    </div>
  );
}

function Section({ title, kicker, children }: { title: string; kicker?: string; children: React.ReactNode }) {
  return (
    <section style={{ marginBottom: 40 }}>
      {kicker && <div style={KICKER}>{kicker}</div>}
      <h2
        style={{
          fontFamily: "var(--font-fraunces)",
          fontSize: 22,
          color: COLORS.text,
          marginTop: 6,
          marginBottom: 18,
        }}
      >
        {title}
      </h2>
      {children}
    </section>
  );
}

function SimpleTable({ head, rows }: { head: string[]; rows: React.ReactNode[][] }) {
  return (
    // overflow-x wrapper so wide tables scroll inside their own box on
    // phones instead of forcing the whole page to scroll sideways.
    <div style={{ borderTop: `1px solid ${COLORS.line}`, overflowX: "auto" }}>
      <table style={{ width: "100%", minWidth: 520, borderCollapse: "collapse" }}>
        <thead>
          <tr>
            {head.map((h, i) => (
              <th
                key={i}
                style={{
                  textAlign: "left",
                  padding: "10px 12px",
                  borderBottom: `1px solid ${COLORS.line}`,
                  ...KICKER,
                  color: COLORS.dim,
                }}
              >
                {h}
              </th>
            ))}
          </tr>
        </thead>
        <tbody>
          {rows.map((r, i) => (
            <tr key={i}>
              {r.map((c, j) => (
                <td
                  key={j}
                  style={{
                    padding: "12px",
                    borderBottom: `1px solid ${COLORS.line}`,
                    color: COLORS.text,
                    fontSize: 13,
                  }}
                >
                  {c}
                </td>
              ))}
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

function Cell({ v, color }: { v: number; color: string }) {
  return <span style={{ color: v > 0 ? color : COLORS.muted }}>{v}</span>;
}

/**
 * A signed percentage with a proportional bar behind it, scaled to the
 * column max. Left-anchored so the eye reads magnitude as length; green
 * up / red down. Rendered in this page's inline-style idiom (not the
 * dashboard <Magnitude>) so the editorial design language is preserved.
 */
function MagBar({ value, max }: { value: number | null; max: number }) {
  const color =
    value == null ? COLORS.muted : value > 0 ? COLORS.pos : COLORS.neg;
  const pct =
    value != null && max > 0 ? Math.min(100, (Math.abs(value) / max) * 100) : 0;
  return (
    <span
      style={{
        position: "relative",
        display: "inline-block",
        minWidth: 96,
        padding: "3px 8px",
      }}
    >
      {value != null && pct > 0 && (
        <span
          aria-hidden
          style={{
            position: "absolute",
            top: 3,
            bottom: 3,
            left: 0,
            width: `${pct}%`,
            background: color,
            opacity: 0.28,
            borderRadius: 2,
          }}
        />
      )}
      <span
        style={{ position: "relative", color, fontVariantNumeric: "tabular-nums" }}
      >
        {value == null ? "—" : fmtPct(value, true)}
      </span>
    </span>
  );
}

function HeadlineCell({
  title,
  fallback,
  href,
}: {
  title: string | null;
  fallback: string | null;
  href: string;
}) {
  // Single-line, character-clamped (CSS line-clamp would need an extra
  // wrapper for ellipsis to play nicely inside table cells). 92 chars
  // is a comfortable upper bound on a 1440px viewport.
  const raw = title?.trim() || fallback || "—";
  const display = raw.length > 92 ? raw.slice(0, 92).trimEnd() + "…" : raw;
  return (
    <a
      href={href}
      title={raw}
      style={{
        color: COLORS.text,
        textDecoration: "none",
        display: "block",
        maxWidth: 520,
        overflow: "hidden",
        textOverflow: "ellipsis",
        whiteSpace: "nowrap",
        fontSize: 13,
      }}
    >
      {display}
    </a>
  );
}

function OutcomeBadge({ outcome }: { outcome: string }) {
  const styles: Record<string, { color: string; label: string }> = {
    target_hit: { color: COLORS.pos, label: "Target" },
    stop_hit: { color: COLORS.neg, label: "Stop" },
    flat: { color: COLORS.muted, label: "Flat" },
    dismissed: { color: COLORS.dim, label: "Dismissed" },
    blocked: { color: COLORS.dim, label: "Blocked" },
  };
  const s = styles[outcome] ?? { color: COLORS.muted, label: outcome };
  return (
    <span
      style={{
        ...KICKER,
        color: s.color,
        fontSize: 10,
        padding: "3px 8px",
        border: `1px solid ${s.color}33`,
        borderRadius: 4,
      }}
    >
      {s.label}
    </span>
  );
}
