/**
 * Derive empirical base rates from the calibration corpus.
 *
 * Produces a (subtype, asset_class) → BaseRate table. Each cell holds:
 *   mean_move_pct   — confidence-weighted mean of |realized_pct_move|
 *   stdev_move_pct  — sample stdev (or fallback when n < 3)
 *   horizon_hours   — confidence-weighted mean of duration_of_impact_days
 *                     converted to hours
 *   sample_size     — count of events contributing to this cell
 *   notes           — short rationale + range
 *
 * Confidence weighting (per spec):
 *   high   → 1.0
 *   medium → 0.7
 *   recent → 0.5  (still-settling outcomes; partial credit)
 *
 * Small-sample handling:
 *   n = 1   stdev defaults to 0.6 * |mean| (wide band) and notes flag
 *           the single-anchor status
 *   n = 2   stdev computed from the pair, floored at 0.4 * |mean|
 *   n ≥ 3   stdev is the unbiased sample stdev
 *
 * Empirical rates take precedence over the legacy hand-curated table
 * (src/lib/pipeline/base_rates.json) in significance scoring (Phase C).
 */

import type { CorpusConfidence, CorpusEvent, CalibrationCorpus } from "./corpus";

export interface DerivedBaseRate {
  mean_move_pct: number;
  stdev_move_pct: number;
  horizon_hours: number;
  sample_size: number;
  notes: string;
}

export interface DerivedBaseRateTable {
  _schema: {
    comment: string;
    generated_at: string;
    source: string;
    fields: Record<string, string>;
  };
  [subtype: string]: Record<string, DerivedBaseRate> | unknown;
}

const CONFIDENCE_WEIGHT: Record<CorpusConfidence, number> = {
  high: 1.0,
  medium: 0.7,
  recent: 0.5,
};

interface Bucket {
  events: CorpusEvent[];
}

/** Group corpus events by (subtype, asset_class). */
function bucketize(events: CorpusEvent[]): Map<string, Map<string, Bucket>> {
  const m = new Map<string, Map<string, Bucket>>();
  for (const e of events) {
    let bySubtype = m.get(e.catalyst_subtype);
    if (!bySubtype) {
      bySubtype = new Map();
      m.set(e.catalyst_subtype, bySubtype);
    }
    let bucket = bySubtype.get(e.asset_class);
    if (!bucket) {
      bucket = { events: [] };
      bySubtype.set(e.asset_class, bucket);
    }
    bucket.events.push(e);
  }
  return m;
}

/**
 * Confidence-weighted mean over a numeric extractor.
 * sum(w_i * x_i) / sum(w_i)
 */
function weightedMean(
  events: CorpusEvent[],
  extract: (e: CorpusEvent) => number,
): number {
  let num = 0;
  let den = 0;
  for (const e of events) {
    const w = CONFIDENCE_WEIGHT[e.confidence];
    num += w * extract(e);
    den += w;
  }
  return den > 0 ? num / den : 0;
}

/**
 * Unbiased sample stdev with confidence weights.
 * For weighted stdev we use the reliability-weighted formula:
 *   variance = sum(w_i * (x_i - mean)^2) / sum(w_i)
 * which assumes weights are reliabilities, not frequencies — appropriate
 * for our confidence tiers.
 */
function weightedStdev(
  events: CorpusEvent[],
  mean: number,
  extract: (e: CorpusEvent) => number,
): number {
  if (events.length === 0) return 0;
  let num = 0;
  let den = 0;
  for (const e of events) {
    const w = CONFIDENCE_WEIGHT[e.confidence];
    const d = extract(e) - mean;
    num += w * d * d;
    den += w;
  }
  return den > 0 ? Math.sqrt(num / den) : 0;
}

function round1(n: number): number {
  return Math.round(n * 10) / 10;
}

export function deriveBaseRates(corpus: CalibrationCorpus): DerivedBaseRateTable {
  const buckets = bucketize(corpus.events);
  const out: DerivedBaseRateTable = {
    _schema: {
      comment:
        "Empirically derived (subtype, asset_class) base rates from the calibration corpus. Generated by scripts/calibrate-base-rates.ts. Do not hand-edit — re-run the script.",
      generated_at: new Date().toISOString(),
      source: `data/calibration-corpus.json (schema_version=${corpus.schema_version})`,
      fields: {
        mean_move_pct:
          "confidence-weighted mean of |realized_pct_move| over corpus events in this cell",
        stdev_move_pct:
          "confidence-weighted stdev, with floors for small samples",
        horizon_hours:
          "confidence-weighted mean of duration_of_impact_days * 24",
        sample_size: "raw count of corpus events contributing to this cell",
        notes: "summary of the cell's empirical range and small-sample flags",
      },
    },
  };

  for (const [subtype, bySubtype] of buckets) {
    const cells: Record<string, DerivedBaseRate> = {};
    for (const [assetClass, bucket] of bySubtype) {
      cells[assetClass] = deriveCell(bucket.events);
    }
    out[subtype] = cells;
  }
  return out;
}

function deriveCell(events: CorpusEvent[]): DerivedBaseRate {
  // Use absolute realised move — direction is captured separately in the
  // event polarity (long/short). Base rate is the magnitude band.
  const absMoves = (e: CorpusEvent) => Math.abs(e.realized_pct_move);
  const meanRaw = weightedMean(events, absMoves);
  const meanRounded = round1(meanRaw);

  let stdev: number;
  let smallSample = "";
  if (events.length === 1) {
    stdev = round1(0.6 * Math.abs(meanRaw) || 1);
    smallSample = " (n=1 single-anchor; stdev = 0.6 * mean)";
  } else if (events.length === 2) {
    const raw = weightedStdev(events, meanRaw, absMoves);
    stdev = round1(Math.max(raw, 0.4 * Math.abs(meanRaw)));
    smallSample = " (n=2; stdev floored at 0.4 * mean)";
  } else {
    stdev = round1(weightedStdev(events, meanRaw, absMoves));
  }

  const horizonHours = round1(
    weightedMean(events, (e) => e.duration_of_impact_days) * 24,
  );

  const moves = events.map(absMoves);
  const minMove = round1(Math.min(...moves));
  const maxMove = round1(Math.max(...moves));

  return {
    mean_move_pct: meanRounded,
    stdev_move_pct: stdev,
    horizon_hours: horizonHours,
    sample_size: events.length,
    notes: `n=${events.length}; range ${minMove}%..${maxMove}%${smallSample}`,
  };
}

/** Look up an entry by (subtype, asset_class). */
export function lookupDerivedRate(
  table: DerivedBaseRateTable,
  subtype: string,
  assetClass: string,
): DerivedBaseRate | null {
  const bucket = table[subtype];
  if (!bucket || typeof bucket !== "object") return null;
  const entry = (bucket as Record<string, DerivedBaseRate>)[assetClass];
  return entry ?? null;
}

/**
 * Cross-class fallback: when (subtype, assetClass) is empty, fall back to
 * the largest sibling bucket for the same subtype. Used by significance
 * scoring so a halving_event on `large_cap_crypto` still gets a magnitude
 * estimate even if the cell is empty (corpus may only have the BTC entry).
 */
export function lookupWithFallback(
  table: DerivedBaseRateTable,
  subtype: string,
  assetClass: string,
): { rate: DerivedBaseRate; from_class: string } | null {
  const direct = lookupDerivedRate(table, subtype, assetClass);
  if (direct) return { rate: direct, from_class: assetClass };
  const bucket = table[subtype];
  if (!bucket || typeof bucket !== "object") return null;
  const entries = Object.entries(bucket as Record<string, DerivedBaseRate>);
  if (entries.length === 0) return null;
  // Pick the cell with the largest sample_size, ties broken by mean magnitude.
  entries.sort((a, b) => {
    const dn = b[1].sample_size - a[1].sample_size;
    if (dn !== 0) return dn;
    return b[1].mean_move_pct - a[1].mean_move_pct;
  });
  return { rate: entries[0]![1], from_class: entries[0]![0] };
}
